version: "3"
services:
  front:
    # build: front
    image: carolinedesousa/prueba-coches-front:latest
    ports:
      - "9402:9402"
    environment:
      - BACKENDHOST=http://back:8080
  back:
    # build: back
    image: carolinedesousa/prueba-coches-back:latest
    ports:
      - "8080:8080"